= lenskit-input-data(7)

== Name

lenskit-input-data - specify input data for LensKit commands.

== Synopsis

LensKit commands use a set of common options for reading input data.

== Description

Several subcommands of [**lenskit**(1)](man:lenskit(1)) allow for input data to be specified.
They all take the same options to control their input data, documented here.

== Primary Input File

LensKit commands can read data in several different ways.  To give the recommendation or model-building
process some data to work with, one of the following mutually-exclusive options must be present:

--ratings-file *FILE*::
Read ratings from the delimited text file *FILE*.

--csv-file *FILE*::
Read ratings from the CSV file *FILE*.  This is identical to passing `--ratings-file=FILE` with `--delimiter=,`.

--tsv-file *FILE*::
Read ratings from the tab-separated file *FILE*. This is identical to passing `--ratings-file=FILE` with `--delimiter=^I`, but doesn't require you to know how to encode tab characters in your shell.

== Input Options

The options in this section provide additional control over the input.

=== Delimited Ratings and Event Files

These options control how events (`--events-file`) or ratings (`--ratings-file`) are parsed.

-d *DELIM*, --delimiter *DELIM*::
Use *DELIM* as the delimiter for delimited text files.  Only effective in conjunction with
    `--ratings-file` or `--events-file`; does not affect the parsing of `--item-names`.

-H *N*, --header-lines *N*::
Skip *N* header lines at the top of the event or ratings file.

-t *TYPE*, --event-type *TYPE*::
When used with `--events-file`, specifies the type of events that are being read from the file.

== See Also

- link:lenskit.1.adoc[*lenskit*(1)]

{% include "footer.adoc" %}